name: unchained
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  fluent_ui:
  bitsdojo_window:
  toml:
  cupertino_icons: ^1.0.8
  url_launcher:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rathole.exe

  fonts:
    - family: MSYH
      fonts:
        - asset: assets/msyh.ttc